# Generated by Django 4.1.4 on 2023-09-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabdb',
            name='learning_rate',
            field=models.FloatField(null=True),
        ),
    ]
